### ISSUE TITLE
Не проходят тесты, если запускать их все сразу.

### ISSUE THREAD

**Issue by eniluck** [coder1coder/Hackathon#195]
Ошибка:
Message: 
System.InvalidOperationException : A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.

Тесты будут проходить, если закомментировать строчку в Hackathon.Jobs.Module

builder.RegisterType<EventStartNotifierBackgroundService>().As<IHostedService>().InstancePerDependency();

**Comment by coder1coder** [comment]
Не актуально, закрываю
