### ISSUE TITLE
Добавить возможность в зависимости от типа команды (открытая или закрытая)  добавить возможность вступить в команду.

### ISSUE THREAD

**Issue by eniluck** [coder1coder/Hackathon#224]
- закрытая по согласованию с овнером через запрос на вступление
- открытая по кнопке "Вступить"

**Comment by coder1coder** [comment]
На текущий момент реализована возможность создавать и отменять запрос на вступление в команду закрытого типа

**Comment by coder1coder** [comment]
Необходимо доработать следующие кейсы:

1. Отображение заявок в закрытую команду для владельца команды
2. Отказ по заявке в закрытую команду владельцем команды с уведомлением
3. Принятие пользователя в качестве участника в закрытую команду владельцем с уведомлением
4. Добавление пользователя в качестве участника открытой команды
5. Убедиться в работоспособности кейса выхода из команды
