### ISSUE TITLE
Скрыть с фронта и запретить на бэке фичу настройки уведомлений мероприятия

### ISSUE THREAD

**Issue by coder1coder** [coder1coder/Hackathon#321]
На фронте скрыть
![image](https://github.com/coder1coder/Hackathon/assets/13835906/6554fc55-07dd-435e-955a-19e4cecc1e86)

На бэке методы пометить на залоченные

**Comment by gorohov09** [comment]
Настройка уведомлений мероприятия происходит в методах Create и Update контроллера EventController. На фронте закомментировал верстку, отвечающую за эту карточку. На бэке убрал свойство ChangeEventStatusMessages из объектов типа CreateEventRequest и UpdateEventRequest, чтобы другие юзеры, кто захочет использовать нашу апишку не через UI не смогли этого сделать
