### ISSUE TITLE
Проверить работоспособность приложения и зафиксировать ошибки

### ISSUE THREAD

**Issue by coder1coder** [coder1coder/Hackathon#359]
Проверить работоспособность приложения и зафиксировать ошибки (порядок действий и условия для воспроизведения)

Здесь можно почитать о какие-то разделах приложения
https://github.com/coder1coder/Hackathon/wiki

**Comment by Proger0014** [comment]
1. После запуска web api, в логи каждую секунду добавляется:

[14:32:49 INF] UnusedFilesDeleteJob Нет неиспользованных файлов для удаления
[14:32:49 DBG] Trigger instruction : NoInstruction
[14:32:50 DBG] Batch acquisition of 1 triggers
[14:32:50 DBG] Calling Execute on job DEFAULT.UnusedFilesDeleteJob

**Comment by coder1coder** [comment]
> 1. После запуска web api, в логи каждую секунду добавляется:
> 
> [14:32:49 INF] UnusedFilesDeleteJob Нет неиспользованных файлов для удаления [14:32:49 DBG] Trigger instruction : NoInstruction [14:32:50 DBG] Batch acquisition of 1 triggers [14:32:50 DBG] Calling Execute on job DEFAULT.UnusedFilesDeleteJob

https://stackoverflow.com/questions/23866452/quartz-cron-trigger-to-run-every-2nd-day

**Comment by Proger0014** [comment]
Отправка email confirmation

EmailSettings:EmailSender настроены на rambler
Логи при нажатии кнопки подтвердить почту

![image](https://github.com/coder1coder/Hackathon/assets/86766969/a9fe5bcd-b3df-4a3e-abae-b04e945d379c)

Почта юзера была и yandex и temp-mail, ни туда, ни туда не приходило.

**Comment by Proger0014** [comment]
В аккаунте администратора (думаю, и в других также будет)

При попытке начать события, если ты не участвуешь и участников 0, выкидывает неизвестную ошибку
Минимальное кол-во участников в команде поставлено в 1
![image](https://github.com/coder1coder/Hackathon/assets/86766969/739cb2ba-1657-4bc1-a6bb-faf601e98ecd)

Также если присоединиться к событию, будет также
![image](https://github.com/coder1coder/Hackathon/assets/86766969/96d23d64-5dd6-4a42-86c6-fe702e09c778)

**Comment by Proger0014** [comment]
При запросе дружбы, в уведомление приходит не никнейм, а BackendTools.Common.Models.Result`1[Hackathon.Common.Models.User.UserModel]

![image](https://github.com/coder1coder/Hackathon/assets/86766969/dc6625d3-0828-4982-84bd-44cff57cf42e)

**Comment by Proger0014** [comment]
неправильно написана инструкция по запуску web api в readme.md.
![image](https://github.com/coder1coder/Hackathon/assets/86766969/6ef00d46-e232-4a76-ab7f-16a2d0269ff9)
5 строчку нужно изменить на:
```pwsh
dotnet run --no-build --project  .\Hackathon.API\Hackathon.API.csproj
```

в противном случае, выдает ошибку:

![image](https://github.com/coder1coder/Hackathon/assets/86766969/930eff6b-963d-403c-8e12-90b40edfa447)

**Comment by Proger0014** [comment]
![image](https://github.com/coder1coder/Hackathon/assets/86766969/1ae2d330-5880-4b21-a975-fe29e35d9113)

мероприятие, правила. если заполнять его без красных строк, то можно добавиться такого переполнения.

**Comment by Proger0014** [comment]
![image](https://github.com/coder1coder/Hackathon/assets/86766969/f6eae9e8-c259-4ab8-94cd-2c16de17c302)

при попытке начать событие, выходит неизвестная ошибка. Все из-за того, что  минимальное кол-во команд - 2, а в событии присоединено было всего 1 команда.

но сообщение не достаточно подробно для создателя события.

Вот, что показывает devtools

![image](https://github.com/coder1coder/Hackathon/assets/86766969/267b1000-7a82-4848-aa3e-c6ab4f292587)

**Comment by Proger0014** [comment]
Проект, изменение гит репозитория проекта..
При обновлении ссылки, пишет, что некорректна.
![image](https://github.com/coder1coder/Hackathon/assets/86766969/47d5e113-c262-4bd6-8963-2b620000d96b)
ссылка, которая использовалась: 
https://github.com/Proger0014/sharely-todo-list/tree/main/

но, если ввести: 
https://github.com/coder1coder/Backend.Tools/tree/develop

то все отрабатывает нормально
![image](https://github.com/coder1coder/Hackathon/assets/86766969/5e031490-92a6-44c3-b9f6-5c838e42c071)

**Comment by Proger0014** [comment]
Проект, изменение гит репозитория проекта.

когда нажимаю на кнопку обновления проекта и нажимаю отмена, ничего не меняю, выходит данный toast снизу:
![image](https://github.com/coder1coder/Hackathon/assets/86766969/55ceb833-d76e-4279-8d4b-4af689cda9ec)

**Comment by Proger0014** [comment]
Событие, чат, чат команды.

когда пытаюсь общаться с командой, через чат, находясь в событии.

то, во-первых, не отображаются участники команды, во-вторых, сообщения не доходят до команды.

при этом, обычный чат команды работает исправно. и общий чат в событии также работает исправно.
