### ISSUE TITLE
В событии не доходят сообщения в чате команды

### ISSUE THREAD

**Issue by Proger0014** [coder1coder/Hackathon#387]
Событие, чат, чат команды.

когда пытаюсь общаться с командой, через чат, находясь в событии.

то, во-первых, не отображаются участники команды, во-вторых, сообщения не доходят до команды.

при этом, обычный чат команды работает исправно. и общий чат в событии также работает исправно.

_Originally posted by @Proger0014 in https://github.com/coder1coder/Hackathon/issues/359#issuecomment-1763432355_

**Comment by coder1coder** [comment]
Перепроверить, возможно уже не актуально

**Comment by Proger0014** [comment]
Не актуально, все отрабатывает исправно благодаря прошлым изменениям
